#@TYPE: Machine
#@NAME: Qualcomm Mahua Compute Reference Device
#@DESCRIPTION: Machine configuration for Qualcomm Mahua Compute Reference Device

require conf/machine/include/qcom-mahua.inc

MACHINE_FEATURES = "efi pci tpm2"

QCOM_DTB_DEFAULT ?= "mahua-crd"

KERNEL_DEVICETREE ?= " \
    qcom/mahua-crd.dtb \
"

MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += " \
    packagegroup-mahua-crd-firmware \
"

# Mahua-CRD and Glymur-CRD share the same partition configuration.
QCOM_CDT_FILE = "cdt_glymur_crd_0.1.0"
QCOM_BOOT_FILES_SUBDIR = "glymur-crd"
QCOM_PARTITION_FILES_SUBDIR ?= "partitions/glymur-crd/nvme"
QCOM_PARTITION_FILES_SUBDIR_SPINOR ?= "partitions/glymur-crd/spinor"

# Mahua-CRD and Glymur-CRD share the same boot firmware and CDT firmware.
QCOM_BOOT_FIRMWARE = "firmware-qcom-boot-glymur"
QCOM_CDT_FIRMWARE = "firmware-qcom-cdt-glymur"
