PACKAGECONFIG:append:qcom = " tests fastcv"

PACKAGECONFIG[tests] = "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON \
    ,-DBUILD_TESTS=OFF,,"

PACKAGECONFIG[samples] = "-DBUILD_EXAMPLES=ON \
    -DINSTALL_BIN_EXAMPLES=ON \
    -DINSTALL_PYTHON_EXAMPLES=ON,-DBUILD_EXAMPLES=OFF,,"

RDEPENDS_${PN}-apps = "${PN}"
