# Add compatible strings for DTBs.
# FIT_DTB_COMPATIBLE[<dtb_name>] = "<compatible-string>"
# This variable maps a DTB name (without .dtb extension) to its
# Device Tree "compatible" string.

FIT_DTB_COMPATIBLE[lemans-evk] = "qcom,qcs9075-iot"
FIT_DTB_COMPATIBLE[monaco-evk] = "qcom,qcs8275-iot"
FIT_DTB_COMPATIBLE[qcm6490-idp] = "qcom,qcm6490-idp"
FIT_DTB_COMPATIBLE[qcs615-ride] = "qcom,qcs615-adp"
FIT_DTB_COMPATIBLE[qcs6490-rb3gen2] = "qcom,qcs6490-iot"
FIT_DTB_COMPATIBLE[qcs6490-rb3gen2-vision-mezzanine] = "qcom,qcs6490-iot-subtype2"
FIT_DTB_COMPATIBLE[qcs8300-ride] = "qcom,qcs8300-adp"
FIT_DTB_COMPATIBLE[qcs9100-ride] = "qcom,qcs9100-qam"
FIT_DTB_COMPATIBLE[qcs9100-ride-r3] = "qcom,qcs9100-qamr2"
FIT_DTB_COMPATIBLE[sa8775p-ride] = "qcom,sa8775p-qam"
FIT_DTB_COMPATIBLE[sa8775p-ride-r3] = "qcom,sa8775p-qamr2"
