# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# Allow PipeWire to access DMA-HEAP when AudioReach is enabled

[Service]
SupplementaryGroups=dmaheap
