name: Monthly job - pre-poulate cache

on:
  schedule:
  - cron: "22 10 28 * *"   # montly job - at "random" time - top of hour can be busy in github

jobs:
  sstate-cache-cleanup:
    if: github.repository_owner == 'qualcomm-linux'
    runs-on: [self-hosted, qcom-sm-u2404, sm-amd64]
    timeout-minutes: 720
    steps:
      - name: Setup Sstate-cache for upcoming month
        run: |
          NEXT_MONTH=$(date -d "$(date +%Y-%m-01) +1 month" +%Y-%m)
          cp -r -v /efs/qli/meta-qcom/sstate-cache-$(date +%Y-%m)/* /efs/qli/meta-qcom/sstate-cache-${NEXT_MONTH}
      - name: Clean up the persistant sstate-cache dir
        run: |
          rm -rf $(find /efs/qli/meta-qcom/sstate-cache-${NEXT_MONTH}/ -maxdepth 2 -type d -ctime +30 -name '*')
